
variables:
  SYSTEM: slc6
  NAME: gitlab-registry.cern.ch/swan/docker-images/systemuser


stages:
    - build
    - test
    - deploy
    - clean


build_final_image:
    stage: build
    script: docker build --compress --squash --rm -t $CI_COMMIT_SHA --build-arg BUILD_TAG=$CI_COMMIT_SHA .
    tags:
        - swan-runner
    only: 
        - /^v.*$/


build_daily:
    stage: build
    script: docker build --compress --rm -t $CI_COMMIT_SHA --build-arg VERSION_NBEXTENSIONS=daily --build-arg CI_PIPELINE=$CI_PIPELINE_ID .
    tags:
        - swan-runner
    except:
        - /^v.*$/


test_all:
    stage: test
    script: python3 /tests/test_image.py --image $CI_COMMIT_SHA --system $SYSTEM
    tags:
        - swan-runner
    only: 
        - /^v.*$/
    when: on_success


test_latest:
    stage: test
    script: python3 /tests/test_image.py --image $CI_COMMIT_SHA --stack latest --system $SYSTEM
    tags:
        - swan-runner
    except: 
        - /^v.*$/
        - web
    when: on_success


test_release:
    stage: test
    script: python3 /tests/test_image.py --image latest:$SYSTEM --system $SYSTEM --stack $STACK --platform $PLATFORM --python $PYTHON
    tags:
        - swan-runner
    only: 
        - web


publish_image:
    stage: deploy
    script:
        - docker tag $CI_COMMIT_SHA latest:$SYSTEM
        - docker tag $CI_COMMIT_SHA $NAME:$CI_COMMIT_TAG
        - docker login gitlab-registry.cern.ch -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker push $NAME:$CI_COMMIT_TAG
        - docker logout
    tags:
        - swan-runner
    only: 
        - /^v.*$/
    except:
        - web
    when: on_success


publish_daily:
    stage: deploy
    script:
        - docker tag $CI_COMMIT_SHA $NAME:daily
        - docker login gitlab-registry.cern.ch -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker push $NAME:daily
        - docker logout
    tags:
        - swan-runner
    only:
        - schedules
    when: on_success


clean_images:
    stage: clean
    script:
        - docker rmi $CI_COMMIT_SHA
    tags:
        - swan-runner
    when: always
